daniiltserin_adwertisment_board:
    resource: "@daniiltserinAdwertismentBoardBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@daniiltserinAdwertismentBoardBundle/Controller/"
    type:     annotation
