ad_index:
    path:     /
    defaults: { _controller: "daniiltserinAdwertismentBoardBundle:AdwertismentSingle:index" }
    methods:  GET

ad_show:
    path:     /{id}/show
    defaults: { _controller: "daniiltserinAdwertismentBoardBundle:AdwertismentSingle:show" }
    methods:  GET

ad_new:
    path:     /new
    defaults: { _controller: "daniiltserinAdwertismentBoardBundle:AdwertismentSingle:new" }
    methods:  [GET, POST]

ad_edit:
    path:     /{id}/edit
    defaults: { _controller: "daniiltserinAdwertismentBoardBundle:AdwertismentSingle:edit" }
    methods:  [GET, POST]

ad_delete:
    path:     /{id}/delete
    defaults: { _controller: "daniiltserinAdwertismentBoardBundle:AdwertismentSingle:delete" }
    methods:  DELETE
